[project]
name = "tos-datasets"
version = "0.1.0"
description = "A collection of TOS datasets"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
